### ISSUE TITLE
CocoaPods push issue with CloudKit subpod

### ISSUE THREAD

**Issue by Thomvis** [Thomvis/FutureProofing#4]
The CloudKit subpod won't compile when pushing to the CocoaPods trunk. It has been commented out for now to be able to make a release at all, but obviously we need a better solution.

**Comment by phimage** [comment]
using

``` ruby
  s.subspec 'CloudKit' do |ss|
     ss.ios.source_files = 'FutureProofing/CloudKit/*'
     ss.osx.source_files = 'FutureProofing/CloudKit/*'
     ss.tvos.source_files = 'FutureProofing/CloudKit/*'
     ss.frameworks = 'CloudKit'
     ss.dependency 'FutureProofing/Core'
  end
```

> pod lib lint --verbose  --subspec=CloudKit
> 
> *\* BUILD SUCCEEDED **
> 
>  -> FutureProofing/CloudKit (0.3.0)
