### ISSUE TITLE
NSURLSession example doesn't seem to work

### ISSUE THREAD

**Issue by kenlaws** [Thomvis/FutureProofing#5]
This is using Xcode 7.3.1. I'm totally willing to assume I'm doing something wrong, but taking the code you've got in the Read Me (plus my init)...

``` swift
let session = NSURLSession(configuration: NetworkServices.sharedInstance.textConfiguration)
let (task, f) = session.dataTaskWithURL(url)
task!.resume()
f.onSuccess { (data, response) in

}.onFailure { error in

}
```

I get "Expression type `NSURLSessionDataTask` is ambiguous without more context."

Does this need updating for Swift 2.2? Or Xcode 7.3.1?

Thanks,

-Ken.

**Comment by phimage** [comment]
There is already an `dataTaskWithURL` (swift 2) or `dataTask(with:` (swift 3) function on `URLSession`, so there is ambiguity

The workaround is to specify the return type, here using swift 3

``` swift
typealias FutureDataTask = (URLSessionDataTask, Future<(Data?, URLResponse?), AnyError>)
let (task, f): FutureDataTask = 
session.dataTask(with: url)
task.resume()
f.onSuccess { (data, response) in

}
f.onFailure { error in

}
```

Maybe FutureProofing can rename it's function to `dataTaskFuture`
